[package]
name = "mosaic-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
mosaic-core = { path = "../mosaic-core" }
mosaic-scheduler = { path = "../mosaic-scheduler" }
thiserror.workspace = true
