[package]
name = "mosaic-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
bytes.workspace = true
clap.workspace = true
mosaic-core = { path = "../mosaic-core" }
mosaic-protocol = { path = "../mosaic-protocol" }
mosaic-store = { path = "../mosaic-store" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
