[package]
name = "plurifold-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
plurifold-core = { path = "../plurifold-core" }
plurifold-scheduler = { path = "../plurifold-scheduler" }
serde.workspace = true
thiserror.workspace = true
